# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: WaveNetSpectrogram #LSTMFeatureExtractor #
  - decoder: UNet1DDecoderLSTM #UNet1DDecoder #TransformerDecoder

exp_name: dummy
phase: test
n_folds: 5
weight:
  exp_name: ${exp_name}
  run_name: single
  file_name: best_model.pth
model_path_list:
  - "/kaggle/input/cmi-model-10y/fx1/runf0/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf0/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf1/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf1/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf2/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf2/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf3/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf3/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf4/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf4/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf5/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf5/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf6/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf6/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf7/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf7/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf8/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf8/model_weights.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf9/best_model.pth"
  - "/kaggle/input/cmi-model-10y/fx1/runf9/model_weights.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run0/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run1/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run2/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run3/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run4/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run5/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run6/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run7/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run8/best_model.pth"
  - "/kaggle/input/cmi-model-5x/exp_final/run9/best_model.pth"
seed: 42
duration: 17280 
downsample_rate: 2 
upsample_rate: 1
batch_size: 32
num_workers: 2
use_amp: true
average_type: "mean"

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4

# post_process
post_process:
  score_th: 0.02
  distance: 10

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "minute"
  - "anglez"
  - "enmo"
  - "anglez_sin"
  - "anglez_cos"
  - "hour_sin"
  - "hour_cos"
  - "anglez_diff_rolling_med_60"
  - "anglez_diff_rolling_mean_60"
  - "anglez_diff_rolling_max_60"
  - "anglez_diff_rolling_min_60"
  - "anglez_diff_rolling_max_min_60"
  - "anglez_diff_rolling_std_60"
  - "anglez_diff_rolling_quantile_25_60"
  - "anglez_diff_rolling_quantile_975_60"
  - "enmo_diff"
  - "enmo_diff_2"
  - "enmo_diff_4"
  - "enmo_diff_8"
  - "enmo_diff_rolling_med_60"
  - "enmo_diff_rolling_mean_60"
  - "enmo_diff_rolling_max_60"
  - "enmo_diff_rolling_min_60"
  - "enmo_diff_rolling_max_min_60"
  - "enmo_diff_rolling_std_60"
  - "enmo_diff_rolling_quantile_25_60"
  - "enmo_diff_rolling_quantile_975_60"
